### ISSUE TITLE
Great Multiupload

### ISSUE THREAD

**Issue by python-force** [gkuhn1/django-admin-multiupload#13]
Hello,

Would like to tell you that's great multiupload.

It works on the iphone and ipad but with 1 problem, it recognizes each photo with name "image", so when you select 10 photos all are named 'image' and then when you upload them it rewrites the same file so you have 10x same images.
![image](https://cloud.githubusercontent.com/assets/770676/5585427/a513add6-9079-11e4-9edb-4b8f1b25fdaa.jpg)

Thank you.
Great job

**Comment by gkuhn1** [comment]
This logic to rewrite the same file is inside the  FileSystemStorage you are using. It is not part of the multiupload library. If you still need help, let me know.

**Comment by python-force** [comment]
Apologies I have already solved that long time ago with aws storages, Thank you
