### ISSUE TITLE
Django 1.11 compatibility

### ISSUE THREAD

**Issue by python-force** [gkuhn1/django-admin-multiupload#22]
It is causing 500 Internal Error...

<img width="1243" alt="screen shot 2017-08-29 at 11 24 45 pm" src="https://user-images.githubusercontent.com/770676/29854009-64119ce8-8d11-11e7-9672-af4314de61f9.png">

**Comment by gkuhn1** [comment]
Master branch is working on Django v1.11.4.
You can reopen this issue If you are still experiencing this issue and can provide better description about the error.

**Comment by python-force** [comment]
Now having this error...

<img width="1331" alt="screen shot 2017-09-03 at 10 40 48 pm" src="https://user-images.githubusercontent.com/770676/30009802-1515ecc0-90f9-11e7-950a-13df9c9b1cc4.png">

Thank you for looking into this...
