### ISSUE TITLE
Syntax - Missing closing tag

### ISSUE THREAD

**Issue by python-force** [gkuhn1/django-admin-multiupload#23]
Here
https://github.com/gkuhn1/django-admin-multiupload/blob/master/multiupload/templates/multiupload/upload.html

`<!--[if gte IE 8]><script src="{% static 'jquery/jquery.xdr-transport.js"></script><![endif]-->`

It should be

`<!--[if gte IE 8]><script src="{% static 'jquery/jquery.xdr-transport.js' %}"></script><![endif]-->`

**Comment by gkuhn1** [comment]
Thanks @python-force. Fixed PR #24 and merged to master.

**Comment by python-force** [comment]
My pleasure. Thank you
